development:
  adapter: postgresql
  database: ranker_development
  encoding: unicode
  user: ranker
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: ranker_test
  encoding: unicode
  user: ranker
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ranker_production
  encoding: unicode
  pool: 5
  timeout: 5000